version: "3.8"

services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: crm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zaphosting18072025
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: crm-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - environments/.env.production
    command: sh -c "npm run migration:run && node dist/src/main.js"

volumes:
  db_data:
